from .shared import *

class SettingsScheduleLayoutMixin:
        def ders_saatleri_arayuzunu_kur(self):
                ana_lay = QVBoxLayout(self.sekme_saatler)
                ana_lay.setContentsMargins(5, 5, 5, 5)
                ha = self.gecici_veri.get("hesap_ayarlari", {})
                grup_oto = QGroupBox("⚡ Otomatik Saat Hesaplayıcı")
                grid = QGridLayout()
                grid.setSpacing(6)

                self.time_ilk_ders = QTimeEdit(QTime.fromString(
                    ha.get("ilk_ders", "08:40"), "HH:mm"))
                self.time_ilk_ders.setDisplayFormat("HH:mm")
                self.spin_sabah_ders = QSpinBox()
                self.spin_sabah_ders.setRange(0, 15)
                self.spin_sabah_ders.setValue(ha.get("sabah_ders", 4))
                self.spin_ogle_sonra_ders = QSpinBox()
                self.spin_ogle_sonra_ders.setRange(0, 15)
                self.spin_ogle_sonra_ders.setValue(ha.get("ogle_sonra_ders", 4))
                self.spin_ders_sure = QSpinBox()
                self.spin_ders_sure.setRange(10, 120)
                self.spin_ders_sure.setValue(ha.get("ders_sure", 40))
                self.spin_teneffus = QSpinBox()
                self.spin_teneffus.setRange(0, 60)
                self.spin_teneffus.setValue(ha.get("teneffus", 15))
                self.spin_ogle_sure = QSpinBox()
                self.spin_ogle_sure.setRange(0, 120)
                self.spin_ogle_sure.setValue(ha.get("ogle_sure", 60))
                self.spin_fark_ogretmen = QSpinBox()
                self.spin_fark_ogretmen.setRange(0, 15)
                self.spin_fark_ogretmen.setValue(ha.get("fark_ogretmen", 2))
                self.spin_sabah_toplanma = QSpinBox()
                self.spin_sabah_toplanma.setRange(0, 30)
                self.spin_sabah_toplanma.setValue(ha.get("sabah_toplanma", 10))
                self.spin_ogle_toplanma = QSpinBox()
                self.spin_ogle_toplanma.setRange(0, 30)
                self.spin_ogle_toplanma.setValue(ha.get("ogle_toplanma", 3))

                grid.addWidget(QLabel("1. Ders:"), 0, 0)
                grid.addWidget(self.time_ilk_ders, 0, 1)
                grid.addWidget(QLabel("Sabah Ders:"), 0, 2)
                grid.addWidget(self.spin_sabah_ders, 0, 3)
                grid.addWidget(QLabel("Öğle Ders:"), 0, 4)
                grid.addWidget(self.spin_ogle_sonra_ders, 0, 5)
                grid.addWidget(QLabel("Ders Süre:"), 1, 0)
                grid.addWidget(self.spin_ders_sure, 1, 1)
                grid.addWidget(QLabel("Teneffüs:"), 1, 2)
                grid.addWidget(self.spin_teneffus, 1, 3)
                grid.addWidget(QLabel("Öğle Arası:"), 1, 4)
                grid.addWidget(self.spin_ogle_sure, 1, 5)
                grid.addWidget(QLabel("Öğr/Öğrt Fark:"), 2, 0)
                grid.addWidget(self.spin_fark_ogretmen, 2, 1)
                grid.addWidget(QLabel("Sabah Toplan:"), 2, 2)
                grid.addWidget(self.spin_sabah_toplanma, 2, 3)
                grid.addWidget(QLabel("Öğle Toplan:"), 2, 4)
                grid.addWidget(self.spin_ogle_toplanma, 2, 5)

                lay_butonlar = QHBoxLayout()
                btn_hesapla_ici = QPushButton("⬇️ Hafta İçine Hesapla")
                btn_hesapla_ici.setObjectName("btn_hesapla")
                btn_hesapla_ici.clicked.connect(lambda: self.otomatik_hesapla("ici"))
                btn_hesapla_sonu = QPushButton("⬇️ Hafta Sonuna Hesapla")
                btn_hesapla_sonu.setObjectName("btn_hesapla")
                btn_hesapla_sonu.clicked.connect(lambda: self.otomatik_hesapla("sonu"))
                lay_butonlar.addWidget(btn_hesapla_ici)
                lay_butonlar.addWidget(btn_hesapla_sonu)
                grid.addLayout(lay_butonlar, 3, 0, 1, 6)

                grup_oto.setLayout(grid)
                ana_lay.addWidget(grup_oto)

                paneller_layout = QHBoxLayout()
                self.grup_hafta_ici = QGroupBox("Hafta İçi Dersleri")
                lay_ici = QVBoxLayout()
                lay_ici_ust = QHBoxLayout()
                self.combo_ici = QComboBox()
                self.combo_ici.addItems(HAFTA_ICI)
                self.combo_ici.currentTextChanged.connect(self.hafta_ici_gun_degisti)
                lay_ici_ust.addWidget(self.combo_ici)

                btn_ekle_ici = QPushButton("➕ Ekle")
                btn_ekle_ici.setStyleSheet("background-color:#2ed573; color:white;")
                btn_ekle_ici.clicked.connect(
                    lambda: self.ders_ekle_cikar("ici", "ekle"))
                btn_sil_ici = QPushButton("➖ Sil")
                btn_sil_ici.setStyleSheet("background-color:#ff4757; color:white;")
                btn_sil_ici.clicked.connect(
                    lambda: self.ders_ekle_cikar("ici", "cikar"))
                lay_ici_ust.addWidget(btn_ekle_ici)
                lay_ici_ust.addWidget(btn_sil_ici)

                lay_ici.addLayout(lay_ici_ust)
                self.check_ici = QCheckBox("Tüm hafta içine yay")
                self.check_ici.setChecked(True)
                lay_ici.addWidget(self.check_ici)

                self.tablo_ici = self.tablo_sablonu_olustur()
                lay_ici.addWidget(self.tablo_ici)
                self.grup_hafta_ici.setLayout(lay_ici)
                paneller_layout.addWidget(self.grup_hafta_ici)

                self.grup_hafta_sonu = QGroupBox("Hafta Sonu Dersleri")
                lay_sonu = QVBoxLayout()
                lay_sonu_ust = QHBoxLayout()
                self.combo_sonu = QComboBox()
                self.combo_sonu.addItems(HAFTA_SONU)
                self.combo_sonu.currentTextChanged.connect(self.hafta_sonu_gun_degisti)
                lay_sonu_ust.addWidget(self.combo_sonu)

                btn_ekle_sonu = QPushButton("➕ Ekle")
                btn_ekle_sonu.setStyleSheet("background-color:#2ed573; color:white;")
                btn_ekle_sonu.clicked.connect(
                    lambda: self.ders_ekle_cikar("sonu", "ekle"))
                btn_sil_sonu = QPushButton("➖ Sil")
                btn_sil_sonu.setStyleSheet("background-color:#ff4757; color:white;")
                btn_sil_sonu.clicked.connect(
                    lambda: self.ders_ekle_cikar("sonu", "cikar"))
                lay_sonu_ust.addWidget(btn_ekle_sonu)
                lay_sonu_ust.addWidget(btn_sil_sonu)

                lay_sonu.addLayout(lay_sonu_ust)
                self.check_sonu = QCheckBox("Tüm hafta sonuna yay")
                self.check_sonu.setChecked(True)
                lay_sonu.addWidget(self.check_sonu)

                self.tablo_sonu = self.tablo_sablonu_olustur()
                lay_sonu.addWidget(self.tablo_sonu)
                self.grup_hafta_sonu.setLayout(lay_sonu)
                paneller_layout.addWidget(self.grup_hafta_sonu)

                ana_lay.addLayout(paneller_layout)
                self.tablo_ici_eski_gun = self.combo_ici.currentText()
                self.tablo_sonu_eski_gun = self.combo_sonu.currentText()
                self.tabloyu_doldur(self.tablo_ici, self.tablo_ici_eski_gun)
                self.tabloyu_doldur(self.tablo_sonu, self.tablo_sonu_eski_gun)

        def tablo_sablonu_olustur(self):
                t = QTableWidget(0, 5)
                t.setHorizontalHeaderLabels(
                    ["Ders", "Toplan", "Öğrenci", "Öğret", "Çıkış"])
                t.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
                t.verticalHeader().setVisible(False)
                return t

