from okul_zil_v4.ui_component_parts.slider import ClickableSlider
from okul_zil_v4.ui_component_parts.song_dialog import SarkiSecPenceresi
from okul_zil_v4.ui_component_parts.title_reader import _okul_basligini_oku
from okul_zil_v4.ui_component_parts.splash_screen import AcilisEkrani
